### PR TITLE
Add the 'ShowItemName' configuration property

### PR DESCRIPTION
**Pull request by deralmas**
This PR adds a very simple configuration option which allows to hide the custom name tag on top of preview items.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Seems fine except the config, perhaps we should change that into a section instead.

**Comment by deralmas** [comment]
I moved them to their own section called `itemPreview`. I must admit though that I don't like this name a lot, but I couldn't figure out a better name.

**Comment by RoboMWM** [comment]
I would just name it the feature name "ShowOffItems" or "ShowOffItemsFeature" and have the two keys be "enabled" and "displayName"/"displayNameTag" or something.

Other than that, looks good to go.

**Comment by deralmas** [comment]
@RoboMWM good idea, I'll change it right away.

**Comment by deralmas** [comment]
Done!

**Review by RoboMWM — APPROVED** [review]

**Pull request merged**
