### PR TITLE
fix chunk loaded check always being true

### PR DESCRIPTION
**Pull request by PhanaticD**

### CODE REVIEW

**Comment by PhanaticD** [comment]
idk why the previous commits are still there

**Comment by RoboMWM** [comment]
cuz u started a new PR from master. Either rebase master or use a new branch pulled fresh from origin.

**Comment by RoboMWM** [comment]
I thought it was world#getChunk that causes it tho, not location#getChunk too? I guess whatever retrieves a Chunk object causes it to load then?

**Comment by PhanaticD** [comment]
yeppp causes a pretty bad chain reaction if a chunk is loaded then unloaded quickly

**Pull request merged**
